### ISSUE TITLE
How to generate the map?

### ISSUE THREAD

**Issue by FrankSalad** [CMAP-REPOS/essentialworkers#3]
The CMAP [page](https://www.cmap.illinois.gov/updates/all/-/asset_publisher/UIMfSLnFfMB6/content/metropolitan-chicago-s-essential-workers-disproportionately-low-income-people-of-color) on essential workers has a beautiful graphical representation of this data overlaid onto Chicago. When I run the script I just get a CSV.

**Comment by matthewstern** [comment]
Hi @FrankSalad, thanks for finding us and opening this issue. The map in the post was made in GIS software by merging the csv this script outputs with a shapefile of census tracts in the region, and overlaying county borders on top of that. Those shapefiles are free to download from various sources, one option being the census website here: https://www.census.gov/cgi-bin/geo/shapefiles/index.php. 

I'm sorry the script doesn't reproduce the map directly in R! This is a goal of ours, but for now we mostly still revert to GIS for mapping.

**Comment by FrankSalad** [comment]
@matthewstern I would like to see where just Health practitioners and other technical occupations (29-0000) and Healthcare support (31-000) folks are concentrated. Would be nice for the site to allow us to pick from the list of industries it includes in the heatmap.

**Comment by matthewstern** [comment]
it certainly would be cool to enable interactivity and filtering online! A few of our staff have been experimenting with [Shiny](https://shiny.rstudio.com/) for applications like this, but we're not currently at a level where we can produce those sorts of interactive widgets regularly. 

If you've modified the script to focus on the occupations you are interested in, you could build out in-R mapping fairly easily using the ggplot2 and sf packages (See [here](https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html)). I've gone ahead and made a brief demo in [this gist](https://gist.github.com/matthewstern/fa985ab2396c0ff9bead5e0ee0a96aaa).  You'll notice only one line of the original code changes -- the addition of `geometry = TRUE` in line 119 of the gist. That is all you need to utilize the tidycensus package to fetch tract geometry for you from the census website. Once you're there, ggplot2 does the rest. At the very end of the gist, you'll find a very simple in-R map that seeks to replicate the first map on the policy update you linked to in your original post in this thread:
```
mutate(
  final,
  essential_binned = cut(essential, 
                         breaks = c(0,.25, .5,1), 
                         labels = c("0-25%", "25-50%", "50%+"))
  ) %>% 
  ggplot(aes(fill = essential_binned,
             geometry = geometry)) +
  geom_sf(color = NA) +
  scale_fill_brewer(palette = "Greens") +
  theme_void()
```
